version: "3.10"

services:
  db:
    image: postgres:15
    container_name: telegram_medical_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: telegram_medical_app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: bash

volumes:
  pgdata:
