version: '3.10'

services:
  app:
    build: .
    env_file: .env  # Load environment variables
    ports:
      - "5000:5000"  # Example port mapping
    depends_on:
      - db
    volumes:
      - .:/app  # Sync local files with container

  db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: